/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * Simple API for managing users and their tasks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDto
 */
export interface TaskDto {
    /**
     * 
     * @type {number}
     * @memberof TaskDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    status?: TaskDtoStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const TaskDtoStatusEnum = {
    Todo: 'TODO',
    InProgress: 'IN_PROGRESS',
    Done: 'DONE'
} as const;
export type TaskDtoStatusEnum = typeof TaskDtoStatusEnum[keyof typeof TaskDtoStatusEnum];


/**
 * Check if a given object implements the TaskDto interface.
 */
export function instanceOfTaskDto(value: object): value is TaskDto {
    return true;
}

export function TaskDtoFromJSON(json: any): TaskDto {
    return TaskDtoFromJSONTyped(json, false);
}

export function TaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function TaskDtoToJSON(json: any): TaskDto {
    return TaskDtoToJSONTyped(json, false);
}

export function TaskDtoToJSONTyped(value?: TaskDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

