/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * Simple API for managing users and their tasks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TaskDto,
} from '../models/index';
import {
    TaskDtoFromJSON,
    TaskDtoToJSON,
} from '../models/index';

export interface GetUserTasksRequest {
    userId: number;
}

/**
 * 
 */
export class TaskApi extends runtime.BaseAPI {

    /**
     * Get tasks for a specific user
     */
    async getUserTasksRaw(requestParameters: GetUserTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserTasks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{userId}/tasks`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskDtoFromJSON));
    }

    /**
     * Get tasks for a specific user
     */
    async getUserTasks(requestParameters: GetUserTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskDto>> {
        const response = await this.getUserTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
